CREATE ROLE ccw_app LOGIN PASSWORD 'localdev';
CREATE DATABASE ccw_orders;

GRANT CONNECT ON DATABASE ccw_catalog TO ccw_app;
GRANT USAGE ON SCHEMA public TO ccw_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ccw_app;

\connect ccw_orders
GRANT CONNECT ON DATABASE ccw_orders TO ccw_app;
GRANT USAGE ON SCHEMA public TO ccw_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ccw_app;
